name: Ingest initiative issue to CSV

on:
  issues:
    types: [labeled]
  workflow_dispatch: {}

jobs:
  ingest:
    if: |
      (github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'ingest') ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Ingest issue into CSV
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          python3 scripts/ingest-issue.py data/initiatives.csv

      - name: Validate CSV
        run: python3 scripts/validate.py data/initiatives.csv

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ingest/issue-${{ github.event.issue.number || github.run_number }}
          title: "Ingest initiative: issue #${{ github.event.issue.number || github.run_number }}"
          commit-message: "Ingest from issue #${{ github.event.issue.number || github.run_number }}"
          body: "This PR was generated from the initiative issue. Please review the CSV changes. No personal contact details are included."
          add-paths: |
            data/initiatives.csv
